version: "3"

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  database:
    image: glassnode/code-challenge-2020-database:latest
    environment:
      POSTGRES_DB: eth
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      frontend:
        ipv4_address: 172.20.0.5
  solution:
    build: .
    depends_on:
      - database
    networks:
      frontend:
        ipv4_address: 172.20.0.6
    ports:
      - "7001:7001"